const SB_URL='https://zodpkvssomalkxjzkpau.supabase.co';
const API=SB_URL+'/functions/v1/class-challenge';
let sb=null;
const signature='تصميم وبرمجة - الحسن علي مدخلي - Kaspersky';
let S={settings:{},students:[],questions:[],leaders:[],round:{status:'closed'},serverNow:Date.now()};
let teacher=null,view='student',tab='setup',grade='',classroom='',selected=null,waiting=false,answers=[],offset=0,timer=null,toastTimer=null,pin='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=ms=>{ms=Math.max(0,ms||0);const m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000),d=Math.floor(ms%1000/100);return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'.'+d};
const uniq=a=>[...new Set(a.filter(Boolean))];
async function req(action,method='GET',body){const u=API+'?action='+encodeURIComponent(action);const r=await fetch(u,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw new Error(j.error||'request_failed');return j}
function toast(t){document.querySelector('.toast')?.remove();const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);clearTimeout(toastTimer);toastTimer=setTimeout(()=>d.remove(),2600)}
async function load(){const next=await req('state');S=next;offset=S.serverNow-Date.now();if(!grade&&S.settings.grade)grade=S.settings.grade;if(!classroom&&S.settings.classroom)classroom=S.settings.classroom;render();return S}
async function loadTeacher(){teacher=await req('teacher-state','POST',{pin});render()}
const nowServer=()=>Date.now()+offset;
function options(arr,current,placeholder='اختر'){return '<option value="">'+placeholder+'</option>'+arr.map(x=>'<option '+(x===current?'selected':'')+'>'+esc(x)+'</option>').join('')}
function statusText(){return S.round.status==='waiting'?'غرفة الانتظار مفتوحة':S.round.status==='countdown'?'العد التنازلي جارٍ':S.round.status==='active'?'التحدي جارٍ':'التحدي مغلق'}
function render(){const app=document.getElementById('app');if(view==='teacher'&&teacher){app.innerHTML=teacherHtml();bindTeacher();return}app.innerHTML=studentHtml();bindStudent();syncStudentPhase()}
function studentHtml(){const grades=uniq(S.students.map(x=>x.grade));const classes=uniq(S.students.filter(x=>!grade||x.grade===grade).map(x=>x.classroom));const students=S.students.filter(x=>x.grade===grade&&x.classroom===classroom);const leaders=(S.leaders||[]).map((r,i)=>'<div class="leader"><span class="rank">'+(i+1)+'</span><div><b>'+esc(r.student)+'</b><small>'+esc(r.grade)+' · '+esc(r.classroom)+'</small></div><strong>'+fmt(r.timeMs)+'</strong></div>').join('')||'<div class="empty">لا توجد نتائج صحيحة مكتملة بعد.</div>';const names=students.map(x=>'<button class="name" data-id="'+x.id+'"><b>'+esc(x.name)+'</b><span>'+esc(x.grade)+' · '+esc(x.classroom)+'</span></button>').join('')||'<div class="empty">اختر الصف والفصل لعرض الأسماء.</div>';return '<div class="page"><div class="top"><div class="brand"><div class="bolt">⚡</div><div><h1>تحدي الصف</h1><p>الأسرع والأدق في الإجابة</p></div></div><button id="teacherBtn" class="ghost">لوحة المعلم</button></div><section class="hero"><h2>'+esc(S.settings.lesson||'في انتظار إعداد المعلم')+'</h2><p>اختر الصف والفصل ثم اسمك، وبعد ذلك ستنتقل إلى غرفة الانتظار.</p><div class="sigHero">'+signature+'</div><div class="pills"><span>'+esc(S.settings.subject||'المادة —')+'</span><span>'+esc(S.settings.grade||'الصف —')+'</span><span>'+esc(S.settings.classroom||'الفصل —')+'</span><span>'+esc(S.settings.period||'الحصة —')+'</span></div></section><div class="layout"><section class="card"><h2>اختر اسمك</h2><p class="note">تم تصغير البطاقات لتظهر أكبر كمية ممكنة من الأسماء على شاشة الجوال.</p><div class="filters"><label>الصف<select id="grade">'+options(grades,grade,'اختر الصف')+'</select></label><label>الفصل<select id="class">'+options(classes,classroom,'اختر الفصل')+'</select></label></div><div class="names">'+names+'</div></section><aside class="card"><h2>المتصدرون</h2><p class="note">الإجابات الكاملة الصحيحة فقط، مرتبة بالأسرع.</p><div class="leaders">'+leaders+'</div>'+(S.prizeUrl?'<img class="prize" src="'+S.prizeUrl+'" alt="الجائزة">':'')+'</aside></div><footer class="note" style="text-align:center;padding:14px">'+esc(S.settings.footerText||'')+'</footer></div>'+waitingHtml()+quizHtml()}
function waitingHtml(){if(!selected||!waiting)return '';let count='';if(S.round.status==='countdown'&&S.round.opensAt){const left=S.round.opensAt-nowServer();count='<div class="count">'+Math.max(0,Math.ceil(left/1000))+'</div>'}const closed=S.round.status==='closed';return '<div class="overlay"><div class="box"><div class="waitIcon">⏳</div><h2>'+(S.round.status==='countdown'?'استعد!':closed?'غرفة الانتظار مغلقة':'أنت الآن في غرفة الانتظار')+'</h2><p>'+(S.round.status==='countdown'?'سيبدأ التحدي لجميع الطلاب بعد:':closed?'انتظر حتى يفتح المعلم غرفة الانتظار.':'ابقَ في هذه الشاشة، ستظهر الأسئلة تلقائيًا عند طرحها.')+'</p><div class="chip">'+esc(selected.name)+' — '+esc(selected.grade)+' — '+esc(selected.classroom)+'</div>'+count+'<div><span class="sigBox">'+signature+'</span></div><button id="leave" class="secondary">تغيير الاسم</button></div></div>'}
function quizHtml(){if(!selected||waiting||S.round.status!=='active'||!S.questions.length)return '';const qs=S.questions.map((q,qi)=>'<div class="q"><h3>'+(qi+1)+'. '+esc(q.text)+'</h3>'+q.answers.map((a,ai)=>'<label class="opt"><input type="radio" name="q'+qi+'" value="'+ai+'" '+(answers[qi]===ai?'checked':'')+'> '+esc(a)+'</label>').join('')+'</div>').join('');return '<div class="overlay"><div class="box quizBox"><div class="qhead"><div><b>'+esc(selected.name)+'</b><small>'+esc(S.settings.subject||'')+' · '+esc(S.settings.lesson||'')+'</small></div><div id="timer" class="timer">00:00.0</div></div>'+qs+'<div><span class="sigBox">'+signature+'</span></div><button id="submit" style="width:100%;margin-top:8px">إرسال الإجابات</button></div></div>'}
function bindStudent(){document.getElementById('teacherBtn')?.addEventListener('click',async()=>{const p=prompt('أدخل رمز لوحة المعلم:');if(!p)return;pin=p;try{await loadTeacher();view='teacher';render()}catch{pin='';alert('رمز المعلم غير صحيح')}});document.getElementById('grade')?.addEventListener('change',e=>{grade=e.target.value;classroom='';render()});document.getElementById('class')?.addEventListener('change',e=>{classroom=e.target.value;render()});document.querySelectorAll('.name').forEach(b=>b.addEventListener('click',()=>{const st=S.students.find(x=>x.id===b.dataset.id);if(!st)return;if(S.settings.grade&&(st.grade!==S.settings.grade||st.classroom!==S.settings.classroom)){toast('هذا التحدي مخصص لفصل آخر');return}selected=st;answers=[];waiting=S.round.status!=='active';if(S.round.status==='active')answers=new Array(S.questions.length).fill(-1);render()}));document.getElementById('leave')?.addEventListener('click',()=>{selected=null;waiting=false;answers=[];clearInterval(timer);render()});document.querySelectorAll('.opt input').forEach(i=>i.addEventListener('change',e=>{const qi=Number(e.target.name.slice(1));answers[qi]=Number(e.target.value)}));document.getElementById('submit')?.addEventListener('click',submit)}
function syncStudentPhase(){clearInterval(timer);if(selected&&waiting){timer=setInterval(async()=>{if(S.round.status==='countdown'&&S.round.opensAt&&S.round.opensAt-nowServer()<=0){try{await load();if(S.round.status==='active'){waiting=false;answers=new Array(S.questions.length).fill(-1);render()}}catch{}}else if(S.round.status==='active'){waiting=false;answers=new Array(S.questions.length).fill(-1);render()}else if(S.round.status==='countdown'){const c=document.querySelector('.count');if(c)c.textContent=String(Math.max(0,Math.ceil((S.round.opensAt-nowServer())/1000))) }},100)}else if(selected&&S.round.status==='active'&&S.round.opensAt){timer=setInterval(()=>{const t=document.getElementById('timer');if(t)t.textContent=fmt(nowServer()-S.round.opensAt)},100)}}
async function submit(){if(!selected||answers.length!==S.questions.length||answers.some(x=>x<0)){toast('أجب عن جميع الأسئلة أولًا');return}try{const r=await req('submit','POST',{studentId:selected.id,answers,roundId:S.round.roundId});toast(r.perfect?'إجابة كاملة صحيحة — أحسنت!':'تم الإرسال — نتيجتك '+r.score+'%');selected=null;waiting=false;answers=[];await load()}catch(e){toast(e.message==='already_submitted'?'تم تسجيل إجابتك مسبقًا':e.message==='round_changed'?'انتهت الجولة الحالية':'تعذر إرسال الإجابة')}}
